version: '3.9'

services:
  maripili:
    image: 050914759395.dkr.ecr.eu-west-3.amazonaws.com/maripili:latest
    container_name: maripili
    restart: always
    env_file:
      - .env

networks:
  default:
    name: primary
    external: true
