version: '3.9'

services:
  maripili:
    image: 050914759395.dkr.ecr.eu-west-3.amazonaws.com/maripili:latest
    container_name: maripili
    restart: always
    env_file:
      - .app.env

  maripili-db:
    image: mongo:6
    container_name: maripili-db
    restart: always
    env_file:
      - .mongo.env
    volumes:
      - ./data:/data/db

networks:
  default:
    name: primary
    external: true
