export const frasesChiquito = [
  '¿Te da cuen?',
  '¡Fistro!',
  '¡Le voy a jasé un número nuevoooorl!',
  '¡Pecaor de la praderar!',
  '¡No puedor, no puedor!',
  '¡No te digo trigor por no llamarte Rodrigo!',
  '¡Asexsuarrr!',
  '¿Cómorr?',
  '¡Hombre malo, violento!',
  '¡Fuegorrrl!',
  '¡Aguaaa, aguaaa!',
  '¡Hijoputarrl!',
  '¡A can demor e narrr!',
  '¡Cobarderr!',
  '¡Al ataquerrrr!',
  'Meretérita',
  'Sieteee caballo que vienennn de Bonanzaaarrlll',
  '¡Ten cuidadínnn no te hagas pupita en el fistro duodenalll!',
  '¡Jarl!',
  '¡Que lo sepas!',
  '¡Hijo míoorrr!',
  '¡Er putaaarrr!',
  '¡Hasta luego Lucasss!',
  '¡Por la gloria de mi madre!',
  'Tienes más pintura que el neceser de Marujita Díaz',
  'Eres más falso que el flequillo del Dioni',
  'Eres más feo que el Fari comiendo limones',
  'Eres más peligroso que un tiroteo en un ascensor',
  '¡Se ha pasao usted con mi bambina! ¡Es usted un torpedo del año cuatro!',
  'Ere ma violento que el entrenador de lo Pogüer Renlle',
  'Trabaja menos que el sastre de Tarzán',
  'Acapiporla',
  'Ay canemor',
  'A güán, a peich, agromenáuer',
  '¡Cuidadín!',
  '¡Te voy a borrar el cerito sesualrllr!',
  '¡Ese fistro danimarl!',
  '¡Te viá cortá el fiistro dabajo!',
  '¡Uno que nació después de los dolores!',
  '¡No puede sé!',
  '¡Es un diodená de persona humana!',
  '¡Un gesto de hombre malo de la pradera!',
  'Apiticain, mor nau',
  'Se mueve uhté mah que los precioh!',
  '¡Relájese usterl!',
  'Relájate físicamente, morálmente',
  'Lo maté en agosto, la calóh apretaba',
  'En vez del graduado escolar tenía una etiqueta de Anís del Mono',
  '¡No compre pan!'
]

export const frasesLopera = [
  'Yo soy diabético, es decir, dos veces bético',
  'Llame usted al Banco Hispanoamericano y dígale al director que no cierre y que se espere',
  'No le hemos dado la alegría a gente con la botella de champán abierta',
  'Estábamos en la UVI; nadie daba un duro por nosotros..yo os entrego ahora un Betis libre, limpio, en Primera, de ustedes, viva el Betis',
  'Ustedes, los béticos, tenéis acolapsada toda La Palmera',
  'Ustedes, los béticos tenéis un jugador que se llama Alfonso que está cedido al Real Madrid',
  'Hemos fichado a un jugador que para que nos lo quiten tienen que cerrar un banco',
  'Aquí teneis la caja de herramientas',
  'Nosotros paseamos un título y otros una sábana pintarrajeá',
  'Me estáis exigiendo que me estáis cansando. Que no me entrampo. Estoy muriendo por el Betis',
  '¿Dónde estaba usted en el 92?',
  '¡Venga, a ustedes!'
]

export const frasesBuenosDias = [
  'GOATED',
  'Alfredo!! Esther pregunta que qué es un test',
  'Nada como la carbonara del manopli',
  'Tabo ven paca tiriririiii',
  'A quien no le va a gustar',
  'Sin animo de lucro de Algeciras',
  'El Doctor Antunes os desea muy buenos días',
  'Esta noche con Stephanie al Sol y Sombra',
  'Po yo me lo he comio!',
  'Amigo amigoo amigoooo',
  'Yo muevo el ratón, pero esto no se enciende',
  'Manopla empleado del año',
  'Vivo con tu madre en un castillo',
  'Good morning people!!!',
  'Eran seis motoristas que eran motos',
  'A mi en inglés no!!',
  'Qué tú dise??',
  'Apetecanemorenao',
  'Oneeeee!!!',
  'Eso va a ser de la cobertura',
  'Tabo haz un dump de la DB que eso es lo tuyo',
  'Arturo más de dos años en la misma empresa.. Quién te ha visto y quién te ve 🤦',
  'Blas!! no encuentro cabras de lunares',
  'No puede ser.. El mundo entero se conmocionó!!',
  'Kubotán en oferta flash ninios!!',
  'Elena vamos a ver el señor de los anillos',
  'Solidaricémonos!! Todos somos el Pepino',
  'De Ayesa a Solera y tiro porque me toca',
  'Oneee!!! Pásate fotitos guarras de Mikael',
  'Pa mi una tota nonmaaa!!',
  'Buenos días nos de Dios',
  'Jola, K ase?',
  'Manopla ayudame con el curso',
  'Juan, para cuando el quinto?',
  'Arturo, déjame la muñeca!'
]

export const frasesMariPili = [
  'A mi no me nombres boca chancla',
  'Desgraciao',
  'A otra a pedirle cosas',
  'Hoy no... Mañanaaa',
  'Traeme unos bocabit tontolava',
  'Tú no eres más tonto porque no te entrenas'
]

const frasesInsultos = [
  'Ablanda brevas',
  'Abrazafarolas',
  'Abrillantaglandes',
  'Afilasables',
  'Alsarrabo',
  'Ambercocat',
  'Anacoluto',
  'Analfabestia',
  'Animal de acequia',
  'Antancanciao',
  'Apollardao',
  'Apollardar',
  'Arrastramantas',
  'Arrastrazapatillas',
  'Arrollapasto',
  'Artosopas',
  'Asalta asilos',
  'Asaltacunas',
  'Asaltapozos',
  'Asustatrenes',
  'Atroplella platos',
  'Bailabainas',
  'Bailaferias',
  'Barjaula',
  'Bastarda',
  'Bastardo',
  'Bebecharcos',
  'Bebesinsed',
  'Bigotezorra',
  'Bobolaverga',
  'Bobomierda',
  'Boborremoto',
  'Bocabuzón',
  'Bocachancla',
  'Bocachocho',
  'Bocafiemo',
  'Bolascombro',
  'Boludo',
  'Brincacepas',
  'Bujarra',
  'Bujarron',
  'Bujarrón',
  'Cabeza alberca',
  'Cabeza de chorlito',
  'Cabezabuque',
  'Cabezakiko',
  'Cabezalpaca',
  'Cabezantorcha',
  'Cabezarrucho',
  'Cabron',
  'Cabrona',
  'Cabronazo',
  'Cabrón',
  'Cacho mierda',
  'Cachomierda',
  'Caga bandurrias',
  'Cagablando',
  'Cagaestacas',
  'Cagalindes',
  'Cagaportales',
  'Cansa almas',
  'Cansaliebres',
  'Cantamañanas',
  'Capulla',
  'Capullo',
  'Capuyo',
  'Caracandao',
  'Caracartón',
  'Carachancla',
  'Caracoño',
  'Caraculo',
  'Caraespatula',
  'Caraestaca',
  'Caraestufa',
  'Caraflema',
  'Carahogaza',
  'Carajaula',
  'Carajote',
  'Caramierda',
  'Caramirlo',
  'Caranabo',
  'Carantigua',
  'Carapan',
  'Carapapa',
  'Carapena',
  'Caraperro',
  'Carapolla',
  'Caraputa',
  'Carasapo',
  'Carasuela',
  'Caxomierda',
  'Cercopiteco',
  'Chafacharcos',
  'Chafalotodo',
  'Chalada',
  'Chalado',
  'Chalao',
  'Chupacables',
  'Chupacharcos',
  'Chupaescrotos',
  'Chupamela',
  'Chupamingas',
  'Chupasangre',
  'Chupatintas',
  'Chupóptero',
  'Cierrabares',
  'Cipote',
  'Comebolsas',
  'Comechapas',
  'Comemierda',
  'Comemierdas',
  'Comemocos',
  'Comepollas',
  'Comeprepucios',
  'Comerreglas',
  'Cornudo',
  'Correveidile',
  'Cuerdalpaca',
  'Cuerpoescombro',
  'Culoalberca',
  'Culotrapo',
  'Descalzaputas',
  'Descosealpargatas',
  'Destiñe rubias',
  'Desvirgagallinas',
  'Empujamierda',
  'Enderezaplátanos',
  'Engaña baldosas',
  'Estas como un manojo de vergas',
  'Follacabras',
  'Follagatos',
  'Follácaros',
  'Forrotimple',
  'Gili',
  'Gilicoño',
  'Gilipichi',
  'Gilipichis',
  'Gilipipas',
  'Gilipollas',
  'Gilipuerta',
  'Gordinflón',
  'Guarrilla',
  'Hartosopa',
  'Hartosopas',
  'Hdp',
  'Hijo da puta',
  'Hijo de chacal',
  'Hijo de cura',
  'Hijo de hiena',
  'Hijo de obispo',
  'Hijueputa',
  'Huelebragas',
  'Julai',
  'Lamecharcos',
  'Lamecirios',
  'Lameculos',
  'Lamehuevos',
  'Lameplatos',
  'Lamerajas',
  'Lameñordos',
  'Ligera de cascos',
  'Ligero de cascos',
  'Limpiatubos',
  'Lumia',
  'Machirulo',
  'Machorra',
  'Malafoya',
  'Malasangre',
  'Malfollada',
  'Malfollado',
  'Malnacida',
  'Malnacido',
  'Malparida',
  'Malparido',
  'Mamacallos',
  'Mamahostias',
  'Mameluco',
  'Mamon',
  'Mamona',
  'Mamón',
  'Mangarranas',
  'Mangurrian',
  'Mangurrián',
  'Manos Gachas',
  'Manos de arbol',
  'Maricón',
  'Mascachapas',
  'Mascaxapas',
  'Masturbamulos',
  'Masturbaperros',
  'Masturbavacas',
  'Mataperros',
  'Me cago en tu madre',
  'Me cago en tu padre',
  'Me cago en tu puta madre',
  'Me cago en tu puto padre',
  'Me cago en tus muertos',
  'Meapilas',
  'Media mierda',
  'Meketrefe',
  'Memo',
  'Mentecato',
  'Mequetrefe',
  'Merluzo',
  'Mierda',
  'Mierdaseca',
  'Mojigato',
  'Monchi',
  'Monigote de feria',
  'Morroescopeta',
  'Morroesfinge',
  'Morroestufa',
  'Morrofiemo',
  'Morroperca',
  'Morroputa',
  'Morros de haba',
  'Muerdealmohadas',
  'Mugrosa',
  'Mugroso',
  'Pagafantas',
  'Pajera',
  'Pajero',
  'Panoli',
  'Panzamelva',
  'Papahostias',
  'Papamoscas',
  'Papanatas',
  'Parguela',
  'Parguelas',
  'Pataliebre',
  'Patasdealambre',
  'Pecholata',
  'Pechopertiga',
  'Peinaburras',
  'Peinaobejas',
  'Peinaovejas',
  'Peinapochas',
  'Pelabombillas',
  'Pelacañas',
  'Pelagatos',
  'Pelalimones',
  'Pelamangos',
  'Pelandrusca',
  'Pelarrabos',
  'Pellizcacristales',
  'Pelo estropajo',
  'Pelotudo',
  'Pendejo',
  'Pichabrava',
  'Pichacorta',
  'Pinchacolillas',
  'Pintamonas',
  'Pisamostoh',
  'Pisaverde',
  'Pollaboba',
  'Pollopera',
  'Pudrecolchones',
  'Puta',
  'Putapénico',
  'Putos',
  'Pánfilo',
  'Retarded',
  'Retrasubnormal',
  'Retropetuda',
  'Robaperas',
  'Saltacequias',
  'Saltinbanquis',
  'Somugroso',
  'Soplagaitas',
  'Soplanucas',
  'Soplasartenes',
  'Subnormala',
  'Subnormalo',
  'Subnorpollas',
  'Sunormal',
  'Tapón de Balsa',
  'Te huele la espalda a baron dandi',
  'Tita freda',
  'Titafluixa',
  'Titafreda',
  'Tocapelotas',
  'Tolai',
  'Tolete',
  'Tonta',
  'Tontaco',
  'Tonto',
  'Tonto dels collons',
  'Tontoculo',
  'Tontoelculo',
  'Tontollapiz',
  'Tontolaba',
  'Tontolava',
  'Tontolculo',
  'Tontolhaba',
  'Tontoligo',
  'Tontoloscojones',
  'Tontopolla',
  'Tontoprofundo',
  'Tontucio',
  'Tragabaldas',
  'Tragaldabas',
  'Tragalefas',
  'Tragalpacas',
  'Tronxamonas',
  'Tuercebotas',
  'Vendehumos',
  'Verga',
  'Vuelcalitros',
  'Xingaflautas',
  'Xupaxarcos',
  'Zampabollos',
  'Zanahorio',
  'Zorra',
  'Zurcemierdas',
  'Zurremierdas'
]

export const insultos = getRegexString(frasesInsultos)

export const respuestasInsultos = [
  'Te voy a tener que lavar la boca con legía',
  'Esa boca niñooo',
  'Así no le hablarás tu a tu padre no??',
  'Como te vuelva a escuchar hablar así te doy un tapaboca que te llevas sin comer semana y media',
  'Cuando hablas así el niño Jesús llora',
  'Vas a ir al infierno con esa boquita',
  'Al final me vas a hacer sacar la alpargata',
  'No me seas niñato'
]

export const voicesChiquito = [
  'AwACAgQAAxkDAAICeGLFguitdIhIoJ7QRq6tV8rzomoGAAJrDQAC8ekpUh476djzaCr1KQQ',
  'AwACAgQAAxkDAAICeWLFgum-kvv49lswEIyz_3dFHqYAA2wNAALx6SlSLDmyVfQAASxRKQQ',
  'AwACAgQAAxkDAAICemLFguk2uUnoMGyfpOB-3702P5vhAAJtDQAC8ekpUjtFpJl3kR1QKQQ',
  'AwACAgQAAxkDAAICe2LFgurKgrRFXJ_dY7unbGa9OxOUAAJuDQAC8ekpUst7kqt9XQrXKQQ',
  'AwACAgQAAxkDAAICfGLFgup56a1qJ1SY-SmNYltkAAEpDAACbw0AAvHpKVIgD-4rqop6qykE',
  'AwACAgQAAxkDAAICfWLFguuOtSRA6D4YTVcZTF2r50IqAAJwDQAC8ekpUiPKlspqi-rfKQQ',
  'AwACAgQAAxkDAAICfmLFgusosJ04YRr0jc5DK-7GztZOAAJxDQAC8ekpUjCj4ptxsF8wKQQ',
  'AwACAgQAAxkDAAICf2LFguzLHrqldVgxPP3lKs7S_74EAAJyDQAC8ekpUqpVHAbagWoXKQQ',
  'AwACAgQAAxkDAAICgGLFguxgF0oL58tZZgSs-GuAEMSFAAJzDQAC8ekpUp0y7GSygi_jKQQ',
  'AwACAgQAAxkDAAICgWLFguy9WD7ZErs2h3LoDW3y3Fw1AAJ0DQAC8ekpUkn-cTPN-5oQKQQ',
  'AwACAgQAAxkDAAICgmLFgu2uOroo9zP2K8gMr-7HCmZwAAJ1DQAC8ekpUoTiBdTRmSdGKQQ',
  'AwACAgQAAxkDAAICg2LFgu5LD3GRD2yYMiAtPV3BROOpAAJ2DQAC8ekpUs_nQ1dm1oVUKQQ',
  'AwACAgQAAxkDAAIChGLFgu43nkIsQD-Eege7PLlvMYTzAAJ3DQAC8ekpUq_iVxjuXjT6KQQ',
  'AwACAgQAAxkDAAIChWLFgu9R3fWJUF_ZcfjLMRd0EfSNAAJ4DQAC8ekpUg2DtupO9sRUKQQ',
  'AwACAgQAAxkDAAIChmLFgu9ILa_lnChEyQ5uUbgBAWZWAAJ5DQAC8ekpUrbhbDkV3iiHKQQ',
  'AwACAgQAAxkDAAICh2LFgvAfXQo2RAxMbGKdbdZcMGWTAAJ6DQAC8ekpUole3k0JJk9EKQQ',
  'AwACAgQAAxkDAAICiGLFgvBPIaulAm8Leydr1Ux8lekFAAJ7DQAC8ekpUsMR9X7jcSIGKQQ',
  'AwACAgQAAxkDAAICiWLFgvHFNkOjD5zcTCxfBqiSHLAVAAJ8DQAC8ekpUn2arUVn2fGwKQQ',
  'AwACAgQAAxkDAAICimLFgvGcnaBm9UbCcOwYqRlI1njuAAJ9DQAC8ekpUgm4S0HDrQbiKQQ',
  'AwACAgQAAxkDAAICi2LFgvIfTmHArsqVdFYRV2RG7LNxAAJ-DQAC8ekpUraaObkjChV1KQQ',
  'AwACAgQAAxkDAAICjGLFgvIWbJd1Nfch1rTuU5FFurn0AAJ_DQAC8ekpUuHu9nAwxB_hKQQ',
  'AwACAgQAAxkDAAICjWLFgvPVrpWwemi6zUMGf96uGzGKAAKADQAC8ekpUoT7jK4XbgmHKQQ',
  'AwACAgQAAxkDAAICjmLFgvO_NOr3DWbnzxsdOURBnhIwAAKBDQAC8ekpUgKOjzoeBC9kKQQ',
  'AwACAgQAAxkDAAICj2LFgvT-xpV9ite084wifzG10h-CAAKCDQAC8ekpUl2IdjG4d6a0KQQ',
  'AwACAgQAAxkDAAICkGLFgvT8CuiMmb25AWjCbidySwoSAAKDDQAC8ekpUlI2nByMyP06KQQ',
  'AwACAgQAAxkDAAICkWLFgvV8yZRtZ7aOocZr2fQYv4MaAAKEDQAC8ekpUn7LjJMfcqQ_KQQ',
  'AwACAgQAAxkDAAICkmLFgvXVG7pJSQHZ4aFGDLgDLbAdAAKFDQAC8ekpUrcpHv_SBWvsKQQ',
  'AwACAgQAAxkDAAICk2LFgvYPfeS7Va4YO6vZ0xlVTdJSAAKGDQAC8ekpUg3qfSUSl3qTKQQ',
  'AwACAgQAAxkDAAIClGLFgvbTkZ8qe26HjgHZ4k12jh1FAAKHDQAC8ekpUhqXk2bmvwjXKQQ',
  'AwACAgQAAxkDAAIClWLFgvcdrYKWceR5iEe-eATZAlJyAAKIDQAC8ekpUgdxxhH6iBz1KQQ',
  'AwACAgQAAxkDAAIClmLFgvcQgPl2UwpWbE7NODslRBp2AAKJDQAC8ekpUvSg7_Dwdyd9KQQ',
  'AwACAgQAAxkDAAICl2LFgvjC5t8PIOUo7YV9zMjHM9W6AAKKDQAC8ekpUl3UgNi3pyD6KQQ',
  'AwACAgQAAxkDAAICmGLFgvg2CF_HNF3Lg33E_EPsQbFxAAKLDQAC8ekpUqo9Gj3Ue4LcKQQ',
  'AwACAgQAAxkDAAICmWLFgvm0K9NO4tPzDLMGWkDo4u0dAAKMDQAC8ekpUjT-BEWssfxvKQQ',
  'AwACAgQAAxkDAAICmmLFgvlUcsRYKdOHZxP2q5dYMuUsAAKNDQAC8ekpUkgLUpJtEhjxKQQ',
  'AwACAgQAAxkDAAICm2LFgvpzXmwK_VbpHlocoLwJ-TsOAAKODQAC8ekpUnzB1VXIQWsmKQQ',
  'AwACAgQAAxkDAAICnGLFgvsMrPzK287tSPxdwx77dAvYAAKPDQAC8ekpUisfl_i_ONdbKQQ',
  'AwACAgQAAxkDAAICnWLFgvulRZTcMS4L0I22fU-5212yAAKQDQAC8ekpUmCa4DKs_bCpKQQ',
  'AwACAgQAAxkDAAICnmLFgvywO3idVcfiNrNDt0cqcso9AAKRDQAC8ekpUmckWlZ7UVUeKQQ',
  'AwACAgQAAxkDAAICn2LFgvx1SEDdO6Yv2y-jpwjDUflzAAKSDQAC8ekpUgtCxI48mvnMKQQ',
  'AwACAgQAAxkDAAICoGLFgv0-pJNfMRjohGbGFu7mSxlYAAKTDQAC8ekpUjhLzm1OmVMaKQQ',
  'AwACAgQAAxkDAAICoWLFgv0gTk5yMLzuO8M6y_NxXuroAAKUDQAC8ekpUv8gjFmUW65vKQQ',
  'AwACAgQAAxkDAAIComLFgv3KDLj33nCPC1OziApwmaEdAAKVDQAC8ekpUvjhrixsNNQdKQQ',
  'AwACAgQAAxkDAAICo2LFgv6OgkNtQXrGH3lqeGsWf9rWAAKWDQAC8ekpUtat3Jxz1ri7KQQ',
  'AwACAgQAAxkDAAICpGLFgv7oso9hnrUkeVqjze6b5T8mAAKXDQAC8ekpUpS-Al7Att6WKQQ',
  'AwACAgQAAxkDAAICpWLFgv8QHad4Gt73Eo0S1d30eqiAAAKYDQAC8ekpUlxsdpEUtiqaKQQ',
  'AwACAgQAAxkDAAICpmLFgv_sWU3BEFFrUuqerEjkMf-DAAKZDQAC8ekpUttBTqz05pOwKQQ',
  'AwACAgQAAxkDAAICp2LFgwABC3YtEJtK6ChxAQK6qEq01QACmg0AAvHpKVIBLKhgdAffqykE',
  'AwACAgQAAxkDAAICqGLFgwE3rNFxT9vJ8ElnWWT723gdAAKbDQAC8ekpUi1OMl8z9MRmKQQ',
  'AwACAgQAAxkDAAICqWLFgwE28IyQ6Mu-6Vx6v9nVGSjkAAKcDQAC8ekpUknuQFO2zq3TKQQ',
  'AwACAgQAAxkDAAICqmLFgwICfAiT0Ko7fZ-JVOY-eJSBAAKdDQAC8ekpUghbfhCCNddfKQQ',
  'AwACAgQAAxkDAAICq2LFgwL6usAEw_-eO4KJ87LC6cB_AAKeDQAC8ekpUqWJg6API4-2KQQ',
  'AwACAgQAAxkDAAICrGLFgwMloc_8HIWZq6EXPsbL0o2pAAKfDQAC8ekpUnpUet_epmUaKQQ',
  'AwACAgQAAxkDAAICrWLFgwOHuvLueDWW-bWTyxBEcwmBAAKgDQAC8ekpUuzQtIgb3B-bKQQ',
  'AwACAgQAAxkDAAICrmLFgwTcEfBuO-2LLEThgVMUFduFAAKhDQAC8ekpUpzogho65omGKQQ',
  'AwACAgQAAxkDAAICr2LFgwTvIX9uOm9n7UiNfvn9aqlMAAKiDQAC8ekpUtXhrLf8sNPJKQQ',
  'AwACAgQAAxkDAAICsGLFgwWd0ZjzWLcIA9rHvDt_Uru5AAKjDQAC8ekpUlF-DL6BWYg8KQQ',
  'AwACAgQAAxkDAAICsWLFgwa_z2YNEFl-soxFg37Ld0xtAAKkDQAC8ekpUgigq2-xenBMKQQ',
  'AwACAgQAAxkDAAICsmLFgwY0T7EIuDBSvO_D_pHKOQo_AAKlDQAC8ekpUh5Dnu2R9NItKQQ',
  'AwACAgQAAxkDAAICs2LFgweQhOuo4wOwZH7LNaJdG8yKAAKmDQAC8ekpUre41q7cJATjKQQ',
  'AwACAgQAAxkDAAICtGLFgwe-ZT0h96hKAxx9Mdin21ZSAAKnDQAC8ekpUna7bxTb_WzzKQQ',
  'AwACAgQAAxkDAAICtWLFgwgSDTwRYjMuR6iMU0TjOgpTAAKoDQAC8ekpUrdCW3zulgABiykE',
  'AwACAgQAAxkDAAICtmLFgwh5uT1ZBlf9xW6tAwXDxddrAAKpDQAC8ekpUn94A_1VDx8LKQQ',
  'AwACAgQAAxkDAAICt2LFgwl0_AxYWuO_zCSa71dAzcaKAAKqDQAC8ekpUqUdQLPSWKFWKQQ',
  'AwACAgQAAxkDAAICuGLFgwlNC_Nsxrce6asbvEM5l8nhAAKrDQAC8ekpUimeFEAK66juKQQ',
  'AwACAgQAAxkDAAICuWLFgwrbM46NhJMjkMakWGo8ZeYPAAKsDQAC8ekpUq7BGeAl6oiEKQQ',
  'AwACAgQAAxkDAAICumLFgwvnVVdguj6Tbi1IQqu2WiAiAAKtDQAC8ekpUiNFTdXGhUA1KQQ',
  'AwACAgQAAxkDAAICu2LFgwugP2zxtWXt-Ma7li9JqNPXAAKuDQAC8ekpUkAdONiaN6gaKQQ',
  'AwACAgQAAxkDAAICvGLFgwz0i0bMUV9DhdJmPvfgSRZsAAKvDQAC8ekpUt8xkBlcgPgZKQQ',
  'AwACAgQAAxkDAAICvWLFgwyVP_FU83vqYqjjZxh-8fTzAAKwDQAC8ekpUpfRu1kYhj7fKQQ',
  'AwACAgQAAxkDAAICvmLFgw2uZ-a_PvCSFOArrKaOya9DAAKxDQAC8ekpUhpLEnGGx7d_KQQ',
  'AwACAgQAAxkDAAICv2LFgw3JDqJ5WpQAASVSTELYRAWPWQACsg0AAvHpKVInB9uxGvBlLSkE',
  'AwACAgQAAxkDAAICwGLFgw4AAWAzl3xT87WpUjq-D8O_kgACsw0AAvHpKVLJgEl9rk-06SkE',
  'AwACAgQAAxkDAAICwWLFgw4WJb80nWh4TnTnwZ_C5RtLAAK0DQAC8ekpUux5ueyYXfLXKQQ',
  'AwACAgQAAxkDAAICwmLFgw8uUX6UaSsCxzObeiLsDuh_AAK1DQAC8ekpUiABMoQ9jwMnKQQ',
  'AwACAgQAAxkDAAICw2LFgxDKXRbIjOzmQEIMHapd7uCOAAK2DQAC8ekpUk9Z5t2vsLNCKQQ',
  'AwACAgQAAxkDAAICxGLFgxC7nRgWedY08rmPeuxEqqbvAAK3DQAC8ekpUsF_8tJAQ5ZbKQQ'
]

export const voicesHomer = [
  'AwACAgQAAxkDAAIC1WLFl5X1lSTD-JvZao5Qtwi8BtIBAAK_DQAC8ekpUik9hjsF4lOMKQQ',
  'AwACAgQAAxkDAAIC1mLFl5a_X82Ogi0l3a6g7yU1CxI5AALADQAC8ekpUoEpDgeWPl-UKQQ',
  'AwACAgQAAxkDAAIC12LFl5eRKkZcCMINS6FXAonywzudAALBDQAC8ekpUnmjM1mD3xvdKQQ',
  'AwACAgQAAxkDAAIC2GLFl5hczlUEyQm2J3KWE2wCboMyAALCDQAC8ekpUumLdbUY6a-iKQQ',
  'AwACAgQAAxkDAAIC2WLFl5m5wI0KyaxTyP2dfLzFcwZIAALDDQAC8ekpUtIsNf996N7HKQQ',
  'AwACAgQAAxkDAAIC2mLFl5qNlSE1yQItYhA7cLA7MuhXAALEDQAC8ekpUvQCQYlRptJ7KQQ',
  'AwACAgQAAxkDAAIC22LFl5ssYiCtwlE1R9vtScvD9J8KAALFDQAC8ekpUmlPuGG7Bh_5KQQ',
  'AwACAgQAAxkDAAIC3GLFl5099Ze8bFRof_nCAk9JcyTxAALGDQAC8ekpUgy8U5xyFBjjKQQ',
  'AwACAgQAAxkDAAIC3WLFl57kEwoNr--CMTliBA_2epE0AALHDQAC8ekpUg9wbCcDTspWKQQ',
  'AwACAgQAAxkDAAIC3mLFl57Vxaol0YKZI696SJKAAWF2AALIDQAC8ekpUne_aLqw205wKQQ',
  'AwACAgQAAxkDAAIC32LFl6AsIlOEB7JCy5jyVfkkOZfiAALJDQAC8ekpUoXDOWeHsmOxKQQ',
  'AwACAgQAAxkDAAIC4GLFl6FTBViqmFl-HWtKWa2t0MfWAALKDQAC8ekpUqDh-JyRtOOnKQQ',
  'AwACAgQAAxkDAAIC4WLFl6Kckwn3ozTny0OPyLL3opoZAALLDQAC8ekpUjxJGXeO8ztJKQQ',
  'AwACAgQAAxkDAAIC4mLFl6LFnaJ-_rlA1eoD1wXqoPT3AALMDQAC8ekpUq_qx-WSLOCCKQQ',
  'AwACAgQAAxkDAAIC42LFl6R8Md7ae586hGlRWGqgFMWBAALNDQAC8ekpUhMDek73wYBgKQQ',
  'AwACAgQAAxkDAAIC5GLFl6ZQ7hbInUjVUgJW6dyehJnCAALODQAC8ekpUhq9Zhh193QRKQQ',
  'AwACAgQAAxkDAAIC5WLFl6eqmu0CxbhCIbs__h2FlJLdAALPDQAC8ekpUu3ISeCSh9viKQQ',
  'AwACAgQAAxkDAAIC5mLFl6nYLIsygmqid9IeNAxou5z_AALQDQAC8ekpUtsddbxYO37lKQQ',
  'AwACAgQAAxkDAAIC52LFl6mmhFDsam000H5OfUFMkEviAALRDQAC8ekpUs0rk6MIS3t5KQQ',
  'AwACAgQAAxkDAAIC6GLFl6oeQfQUqzzGtJ5RqS_tQEhQAALSDQAC8ekpUlm868LFwV11KQQ',
  'AwACAgQAAxkDAAIC6WLFl6tOTWyFz6neMYmLoxXiXQNNAALTDQAC8ekpUpNXUBW6-eIRKQQ',
  'AwACAgQAAxkDAAIC6mLFl60gFLUh-BD5yzPMWtYcyDuqAALUDQAC8ekpUuLh4TLJLG3zKQQ',
  'AwACAgQAAxkDAAIC62LFl64ZQvsnwAv-0vbzqF1RboOMAALVDQAC8ekpUrN8nLcM232yKQQ',
  'AwACAgQAAxkDAAIC7GLFl7CXS0EOfzfjOCTfyl1wb2UhAALWDQAC8ekpUs-T3pjVkC78KQQ',
  'AwACAgQAAxkDAAIC7WLFl7F5hRZ9QyV2M2i9cTTMCqcFAALXDQAC8ekpUiFkkLYzlUlwKQQ',
  'AwACAgQAAxkDAAIC7mLFl7LqSjJcle0EnN728xRzWj-wAALYDQAC8ekpUvRhPf2vqgybKQQ',
  'AwACAgQAAxkDAAIC72LFl7MJe8zQ1PUBsFOnqhtWLdHyAALZDQAC8ekpUonSLf6gOOMWKQQ',
  'AwACAgQAAxkDAAIC8GLFl7RWcivMEtayxhOZ8g4Do8ZWAALaDQAC8ekpUkVrYR1Xo62BKQQ',
  'AwACAgQAAxkDAAIC8WLFl7VFK4x27hdJdcaa0Yy5SqQrAALbDQAC8ekpUtoh00wftGG-KQQ',
  'AwACAgQAAxkDAAIC8mLFl7bzrQFJO9hBiJjAGUyajJ5jAALcDQAC8ekpUhdE81uV26M1KQQ',
  'AwACAgQAAxkDAAIC82LFl7g2lCafF5ITiVieS5HjP14hAALdDQAC8ekpUpFRml2XCf09KQQ',
  'AwACAgQAAxkDAAIC9GLFl7lgJQe_tJKRZcvjf0B5J3aTAALeDQAC8ekpUp9M5LQlInt4KQQ',
  'AwACAgQAAxkDAAIC9WLFl7o_9S0cmIWN9JQoJPGGIpjoAALfDQAC8ekpUifDEL5RNzNiKQQ',
  'AwACAgQAAxkDAAIC9mLFl7vaOyJ64tT6rh0UiIOFxc5tAALgDQAC8ekpUoxISzbTbgZLKQQ',
  'AwACAgQAAxkDAAIC92LFl7yY6e0FkAxgT6QYUrx1Fa6AAALhDQAC8ekpUtgdPuex8-B-KQQ',
  'AwACAgQAAxkDAAIC-GLFl72KVGDCMFLDCH9nZHMxlxRvAALiDQAC8ekpUkq5g60rNj4wKQQ',
  'AwACAgQAAxkDAAIC-WLFl7-hIK72wb3IoN_CCNPf6L1BAALjDQAC8ekpUpglscdar_z_KQQ',
  'AwACAgQAAxkDAAIC-mLFl78etDkNRi0d8-53GPKYMM01AALkDQAC8ekpUhjPJeCH4MiKKQQ',
  'AwACAgQAAxkDAAIC-2LFl8AOBHgPtnhCzpmfjRMrWhxUAALlDQAC8ekpUncL3wQEUs_8KQQ',
  'AwACAgQAAxkDAAIC_GLFl8HDG7ofvlk486WHd6hQssoAA-YNAALx6SlSrUiU-cIa9pEpBA',
  'AwACAgQAAxkDAAIC_WLFl8KeqQl2eeINmfSycOkiW393AALnDQAC8ekpUi36KAifLKHRKQQ',
  'AwACAgQAAxkDAAIC_mLFl8NMMjmmDCFDY-hh3n1aFvk8AALoDQAC8ekpUh54RmX1-tELKQQ',
  'AwACAgQAAxkDAAIC_2LFl8OYt5y8lOXcTwGoCAbeA-qTAALpDQAC8ekpUoAL69y6dvdQKQQ',
  'AwACAgQAAxkDAAIDAAFixZfEn52e148YV9Ivwd0LQiLHSAAC6g0AAvHpKVINPHXSebAYPCkE',
  'AwACAgQAAxkDAAIDAWLFl8UG7PnylEP4V2N2wXeD9qvrAALrDQAC8ekpUsU06eiv9xrFKQQ',
  'AwACAgQAAxkDAAIDAmLFl8Y5aKA3eXV14g3ve2KWBf8lAALsDQAC8ekpUsBqqbKAmnPrKQQ',
  'AwACAgQAAxkDAAIDA2LFl8dtqVczx6SPx7Ajh1f6Fc4LAALtDQAC8ekpUrOHJamhSHoFKQQ',
  'AwACAgQAAxkDAAIDBGLFl8hkrUFUgO5xmWNSdCA5B9hlAALuDQAC8ekpUgqk2zjoHPY7KQQ',
  'AwACAgQAAxkDAAIDBWLFl8tnm7IoO1iafpJ_waIXSc5BAALvDQAC8ekpUlw6esP2WcpSKQQ',
  'AwACAgQAAxkDAAIDBmLFl808KNXs7M3PYPqdavDpDr17AALwDQAC8ekpUmKzpTGQAAFUjykE',
  'AwACAgQAAxkDAAIDB2LFl82iiroOgB3JLUIzilj8GNNpAALxDQAC8ekpUkllIYGBZnQOKQQ',
  'AwACAgQAAxkDAAIDCGLFl84qAgL3bm1rwLVYs0EMaev0AALyDQAC8ekpUhrVidMLF7NDKQQ',
  'AwACAgQAAxkDAAIDCWLFl8_6v5qzlv8sO-y8advE5aF1AALzDQAC8ekpUpLIlVx956q_KQQ',
  'AwACAgQAAxkDAAIDCmLFl9BtvECmEQxaV6Inu5Vj5gODAAL0DQAC8ekpUs6iCqjUXmM8KQQ',
  'AwACAgQAAxkDAAIDC2LFl9GldCTCkUOxE8yEKN1W7Dg-AAL1DQAC8ekpUgyCWAI81mW6KQQ',
  'AwACAgQAAxkDAAIDDGLFl9N9sZgAAT95QL9dhck1OVe2wAAC9g0AAvHpKVI5eRcYamuMIikE',
  'AwACAgQAAxkDAAIDDWLFl9Q8JSnZnw79_wFI9H6YscrrAAL3DQAC8ekpUuN9UXGMrd7EKQQ',
  'AwACAgQAAxkDAAIDDmLFl9VILYWYxJ6SJLFW4YpLhDmzAAL4DQAC8ekpUrxoQ3UMb8g4KQQ',
  'AwACAgQAAxkDAAIDD2LFl9ZZJ9k8Zs4SuhwpaUA50uXcAAL5DQAC8ekpUig5e-8mWgABTykE',
  'AwACAgQAAxkDAAIDEGLFl9faHqXCX0kr5tOQkArOrCP9AAL6DQAC8ekpUurJEjGEW8VwKQQ',
  'AwACAgQAAxkDAAIDEWLFl9hjH9xbrnKcv7rLhTGVWk8WAAL7DQAC8ekpUtNMwGL-8O2lKQQ',
  'AwACAgQAAxkDAAIDEmLFl9l962p0kdEeq10etCypyyboAAL8DQAC8ekpUiczfFNor0CIKQQ',
  'AwACAgQAAxkDAAIDE2LFl9p-JhgsCk34HfxiYPJeaGlkAAL9DQAC8ekpUq66dZOB75bvKQQ',
  'AwACAgQAAxkDAAIDFGLFl9ux0g1lr5B-ypJZ7lkL02aHAAL-DQAC8ekpUqNVShL6F3GWKQQ',
  'AwACAgQAAxkDAAIDFWLFl9wSDvQ2-snNXOIZTcILiQziAAL_DQAC8ekpUlpQ-bvreSwiKQQ',
  'AwACAgQAAxkDAAIDFmLFl91zGbdXuN4uODSt5pglTs-zAAMOAALx6SlS_y87X5YZVuUpBA',
  'AwACAgQAAxkDAAIDF2LFl97FZ2ln4KZknHkBzOy9hTTeAAIBDgAC8ekpUmq2MZMBC34GKQQ',
  'AwACAgQAAxkDAAIDGGLFl-AJ62QGF2diSzQIULOXp51fAAICDgAC8ekpUvhHeuhxr4CuKQQ',
  'AwACAgQAAxkDAAIDGWLFl-GDdMdn0goZdMGYscj9gv5iAAIDDgAC8ekpUvB2LcmjN0ELKQQ',
  'AwACAgQAAxkDAAIDGmLFl-KcfYzPMqrOZOpWbNHVjkW5AAIEDgAC8ekpUhj6AAEX_DgpeykE',
  'AwACAgQAAxkDAAIDG2LFl-PiS1iC2klsoh33gI6j0nl5AAIFDgAC8ekpUkBNfjQkBRLDKQQ',
  'AwACAgQAAxkDAAIDHGLFl-PXDBdUdI_wTlRCuZ7hAQABDQACBg4AAvHpKVKfCrQVy6I9mykE',
  'AwACAgQAAxkDAAIDHWLFl-QSfvm6QNhtSxLD2uG-_wVNAAIHDgAC8ekpUhj6Zz7R7GbQKQQ',
  'AwACAgQAAxkDAAIDHmLFl-Vt1qCgU-KUSnqrIqwtOgGdAAIIDgAC8ekpUrX-yJ8BqfK8KQQ',
  'AwACAgQAAxkDAAIDH2LFl-WhoE5Us7b68iozyPK_yyiqAAIJDgAC8ekpUjLWUkYq_cEzKQQ',
  'AwACAgQAAxkDAAIDIGLFl-ahPDlzv38L9GdhYrTWvXIYAAIKDgAC8ekpUhsC7W_4G3SEKQQ',
  'AwACAgQAAxkDAAIDIWLFl-eoaq3YvsYCFLPYdldTx5JoAAILDgAC8ekpUjLs8sqQPuDLKQQ',
  'AwACAgQAAxkDAAIDImLFl-j0o8yIsjTuBWgIqMg7N-czAAIMDgAC8ekpUqmsqGcSMp0SKQQ',
  'AwACAgQAAxkDAAIDI2LFl-lKyLPYI2r-i9M4ULBj-GdmAAINDgAC8ekpUl9PG-Y6mPklKQQ',
  'AwACAgQAAxkDAAIDJGLFl-q3sdG43WarsPQVzX0pmJ3bAAIODgAC8ekpUlhKy87yozjxKQQ',
  'AwACAgQAAxkDAAIDJWLFl-rNUsKAFC3kQTWt2r4w43PUAAIPDgAC8ekpUihDc9j05QS2KQQ',
  'AwACAgQAAxkDAAIDJmLFl-uRktQNQpfX9ENGpFFk6WCpAAIQDgAC8ekpUjOZe7b2i9EnKQQ',
  'AwACAgQAAxkDAAIDJ2LFl-yKcYAzOegZa_9yqfh_c-eFAAIRDgAC8ekpUuYgmEUvPavDKQQ',
  'AwACAgQAAxkDAAIDKGLFl-6pFBr6FKSkEU3Wkz715ljWAAISDgAC8ekpUhs3hOp3IRJBKQQ',
  'AwACAgQAAxkDAAIDKWLFl-8mCevU6WcoQ38oESxoNP_8AAITDgAC8ekpUhufX61GFjVbKQQ',
  'AwACAgQAAxkDAAIDKmLFl_BKQv_WndLeRfsNf6P_4KqsAAIUDgAC8ekpUhjxDuHGN3cQKQQ',
  'AwACAgQAAxkDAAIDK2LFl_EAAZmsa-wAAb1C4-clcdPbELsAAhUOAALx6SlS94ErxUUPZZopBA',
  'AwACAgQAAxkDAAIDLGLFl_IgNcOKlj9flrd2LBc9GF-bAAIWDgAC8ekpUu-Tj8zZYESHKQQ',
  'AwACAgQAAxkDAAIDLWLFl_OYolkzrhaN8B_S6p__NmMNAAIXDgAC8ekpUlR1J4gDDQtNKQQ',
  'AwACAgQAAxkDAAIDLmLFl_OBbOQYqnw1PqC6w6U5xYb5AAIYDgAC8ekpUl86U3b5ed8BKQQ',
  'AwACAgQAAxkDAAIDL2LFl_Sj5L_BH6I8MOV8WjECB8fvAAIZDgAC8ekpUvO93MW2IJ4CKQQ',
  'AwACAgQAAxkDAAIDMGLFl_WWkx4bwqg7FGPkdZjpHASZAAIaDgAC8ekpUlPURXE5B4OaKQQ',
  'AwACAgQAAxkDAAIDMWLFl_bWoKuaLGeKt99yhHyMoBN1AAIbDgAC8ekpUofNL-FzSF0SKQQ',
  'AwACAgQAAxkDAAIDMmLFl_fZrZpoM80dF60C-_3oR-uLAAIcDgAC8ekpUr1gzd7KxohhKQQ',
  'AwACAgQAAxkDAAIDM2LFl_f5bPz2aOHaQIZSP_w9SkxaAAIdDgAC8ekpUpXmCKbHu7MJKQQ',
  'AwACAgQAAxkDAAIDNGLFl_iABxpoPJCh2ixmE1Jh21eHAAIeDgAC8ekpUrZiqV4u-43IKQQ',
  'AwACAgQAAxkDAAIDNWLFl_mI_prSdKpVF6GpdrE_MSuhAAIfDgAC8ekpUuO51-1IqFhwKQQ',
  'AwACAgQAAxkDAAIDNmLFl_rJCoAJbdEjXH_eia8SxdukAAIgDgAC8ekpUnsKN16IStN6KQQ',
  'AwACAgQAAxkDAAIDN2LFl_vvQmbYW_4as4qfyOfgZXtoAAIhDgAC8ekpUt4lN76-316-KQQ',
  'AwACAgQAAxkDAAIDOGLFl_zSHfl_k8Auq2x2mRy8Nt1qAAIiDgAC8ekpUvRC-I0YVGi7KQQ',
  'AwACAgQAAxkDAAIDOWLFl__HCogn2YFTTczM2p81knwEAAIjDgAC8ekpUlnoTs1YKeuYKQQ',
  'AwACAgQAAxkDAAIDOmLFmAABPj3-cPp8teiA0_N6tulHpQACJA4AAvHpKVLoTRsrnDkOlCkE',
  'AwACAgQAAxkDAAIDO2LFmAE2shYz_iHYNSHmTVBEhMcJAAIlDgAC8ekpUlK2t1tnqOGOKQQ',
  'AwACAgQAAxkDAAIDPGLFmAI2QCe62eZitvathHrpduiRAAImDgAC8ekpUnHaFjfcqK3hKQQ',
  'AwACAgQAAxkDAAIDPWLFmANCrMJ0BqxyKDNXuNXqEA6rAAInDgAC8ekpUgHUnpmYA9ctKQQ',
  'AwACAgQAAxkDAAIDPmLFmAQxA8TIZAiIwWE58FDg-mGbAAIoDgAC8ekpUlXmMzgYyh8lKQQ',
  'AwACAgQAAxkDAAIDP2LFmASGp0mu3MmHOn6tB2tlRBWDAAIpDgAC8ekpUlWv3sk_6V5lKQQ',
  'AwACAgQAAxkDAAIDQGLFmAWbWKrm4wp-uF_jjd-9dVcHAAIqDgAC8ekpUksZl0FcsGLGKQQ',
  'AwACAgQAAxkDAAIDQWLFmAYCNJPnkp1HERijDY1NAwwIAAIrDgAC8ekpUo_oPchrGMzVKQQ',
  'AwACAgQAAxkDAAIDQmLFmAdtnXoAARX2n5n4XdFKB2WVlQACLA4AAvHpKVJk67RaakT4ASkE',
  'AwACAgQAAxkDAAIDQ2LFmAnfIpJIAtWW1JOfpI2Nw_5bAAItDgAC8ekpUpt64qDIfdhWKQQ',
  'AwACAgQAAxkDAAIDRGLFmAoU2t4nQpe2rxein-aA3uVgAAIuDgAC8ekpUkqzXWUmRLZNKQQ',
  'AwACAgQAAxkDAAIDRWLFmAu7QLJ_SSg9V6q2wim1cWnrAAIvDgAC8ekpUph6KcF3WbY3KQQ',
  'AwACAgQAAxkDAAIDRmLFmAsNL0FpUL83w6loTdk0-FTLAAIwDgAC8ekpUnGgV3DHEoWzKQQ',
  'AwACAgQAAxkDAAIDR2LFmAxaF6ympoVd0smwZC1eY01fAAIxDgAC8ekpUjlSYXWWX1EFKQQ',
  'AwACAgQAAxkDAAIDSGLFmA2vZMqiHqVOKSdnb8xW4vLfAAIyDgAC8ekpUmT26jLHVd3_KQQ',
  'AwACAgQAAxkDAAIDSWLFmA5sSKHY_Mc9nlpy0pLzpHjlAAIzDgAC8ekpUsjtodPqgFX2KQQ',
  'AwACAgQAAxkDAAIDSmLFmA6_WOr4HGRMCGPyREm4_cJNAAI0DgAC8ekpUneAiZOdjKu0KQQ',
  'AwACAgQAAxkDAAIDS2LFmA8lMZO4cHa3uqLLY4HT2E1ZAAI1DgAC8ekpUg4K9w_ZVpHgKQQ',
  'AwACAgQAAxkDAAIDTGLFmBCAyJ1EsbyOOpd-iZJwY-SPAAI2DgAC8ekpUoe0LXW-a-qnKQQ',
  'AwACAgQAAxkDAAIDTWLFmBDVygTSKgABQVs6HrIeLmjq5AACNw4AAvHpKVKjkyDp4jRVDikE',
  'AwACAgQAAxkDAAIDTmLFmBFGhB_WQf7pVtlkn2AudSq5AAI4DgAC8ekpUlYIi_Nx2XFJKQQ',
  'AwACAgQAAxkDAAIDT2LFmBKpt9pRXB9regyj-qqRKQWEAAI5DgAC8ekpUql_fL4ZnNPHKQQ',
  'AwACAgQAAxkDAAIDUGLFmBMzJUZu_Sr80_XhYY1NMuWgAAI6DgAC8ekpUhVukZJRZe24KQQ',
  'AwACAgQAAxkDAAIDUWLFmBTJebRpiUNz2OaShlyUTBb6AAI7DgAC8ekpUjixLuRAVkSBKQQ',
  'AwACAgQAAxkDAAIDUmLFmBZXcXbLbBQZwR-eRYTZYcSoAAI8DgAC8ekpUmnv47kM7X5SKQQ'
]

function getRegexString(array) {
  let result = ''
  array.forEach((element, index) => {
    if (index === 0) {
      result = result + element
    } else {
      result = result + '|' + element
    }
  })
  return result
}
