name: Build And Deploy

on:
  pull_request:
    types:
      - closed
  push:
    tags: ['v*.*.*']

env:
  # github.repository as <account>/<repo>
  REPOSITORY: maripili
  SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
  SSH_PORT: ${{secrets.SSH_PORT}}
  SSH_USER: ${{secrets.SSH_USER}}
  SSH_HOST: ${{secrets.SSH_HOST}}

jobs:
  incrementVersion:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - run: git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - run: git config user.name "$GITHUB_ACTOR"
      - run: npm version patch
      - run: git push "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git" --follow-tags

  buildAndPush:
    needs: incrementVersion
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get the version
        id: get_version
        run: echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2 # More information on this action can be found below in the 'AWS Credentials' section
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET_KEY }}
          aws-region: eu-west-3

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build the Docker image
        run: docker build --build-arg VERSION=${{ steps.get_version.outputs.VERSION }} --build-arg BUILD_DATE="$(date +%Y/%m/%dT%H:%M:%S)" --file Dockerfile --tag ${{ steps.login-ecr.outputs.registry }}/$REPOSITORY:${{ steps.get_version.outputs.VERSION }} .

      - name: Push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ steps.get_version.outputs.VERSION }}
        run: docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: Update latest the Docker image
        run: docker tag ${{ steps.login-ecr.outputs.registry }}/$REPOSITORY:${{ steps.get_version.outputs.VERSION }} ${{ steps.login-ecr.outputs.registry }}/$REPOSITORY:latest

      - name: Push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: latest
        run: docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/private.key
          sudo chmod 600 ~/.ssh/private.key
          ssh-keyscan -p 22022 -H $SSH_HOST > ~/.ssh/known_hosts
        shell: bash

      - name: Copy resources to remote
        run: scp -P $SSH_PORT -i ~/.ssh/private.key -r docker-compose.yml $SSH_USER@$SSH_HOST:~/docker/maripili/docker-compose.yml
        shell: bash

      - name: Deploy service in remote
        run: ssh -t -t -p $SSH_PORT -i ~/.ssh/private.key $SSH_USER@$SSH_HOST "docker login -u AWS -p $(aws ecr get-login-password --region eu-west-3) 050914759395.dkr.ecr.eu-west-3.amazonaws.com && cd ~/docker/maripili && docker compose pull && docker compose up -d"
        shell: bash
